version: "3.2"

services:

  web:
    build: 
      context: ./webserver
    volumes:
      - weblog:/var/log/nginx/
    restart: always

  proxy:
    build:
      context: ./proxy
    volumes:
      - proxylog:/var/log/nginx/
    ports:
      - 8080:80
    restart: always

volumes:
  weblog:
  proxylog:
